#!/usr/bin/env bash
# Install the dgx-spark-bar agent on a DGX Spark. Idempotent: re-running upgrades the
# binary and unit but never rewrites an existing /etc/dgx-spark-bar/agent.conf, so
# local edits survive an upgrade.
#
#   sudo ./install.sh
#
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_DIR=/etc/dgx-spark-bar
CONF="$CONF_DIR/agent.conf"

if [[ $EUID -ne 0 ]]; then
  echo "install.sh must run as root: sudo $0" >&2
  exit 1
fi

TARGET_USER="${SPARKBAR_USER:-${SUDO_USER:-}}"
if [[ -z "$TARGET_USER" || "$TARGET_USER" == "root" ]]; then
  echo "Set SPARKBAR_USER to the non-root user the agent should run as." >&2
  exit 1
fi

echo "==> agent binary"
install -m 0755 "$SRC/dgx_spark_bar_agent.py" /usr/local/bin/dgx-spark-bar-agent

echo "==> config"
install -d -m 0755 "$CONF_DIR"
if [[ -f "$CONF" ]]; then
  echo "    $CONF exists — kept as is"
else
  DISKS="/"
  if mountpoint -q /home 2>/dev/null; then DISKS="/,/home"; fi

  cat > "$CONF" <<EOF
# dgx-spark-bar agent — generated by install.sh on $(date -Is)
# No authentication: private networks only. See agent.conf.example.
BIND=0.0.0.0
PORT=8765

DISKS=$DISKS

WARN_DISK_PCT=85
WARN_GPU_TEMP=85
CRIT_GPU_TEMP=90
EOF
  echo "    wrote $CONF"
fi
chown root:"$TARGET_USER" "$CONF"
chmod 0644 "$CONF"

PORT="$(sed -n 's/^PORT=//p' "$CONF" | head -1)"
PORT="${PORT:-8765}"

echo "==> sudo rights (poweroff + reboot only)"
printf '# installed by dgx-spark-bar — deliberately only these two commands\n%s ALL=(root) NOPASSWD: /usr/sbin/poweroff, /usr/sbin/reboot\n' \
  "$TARGET_USER" > /etc/sudoers.d/dgx-spark-bar
chmod 0440 /etc/sudoers.d/dgx-spark-bar
visudo -cf /etc/sudoers.d/dgx-spark-bar >/dev/null

echo "==> systemd unit"
sed "s/@USER@/$TARGET_USER/g" "$SRC/dgx-spark-bar-agent.service" \
  > /etc/systemd/system/dgx-spark-bar-agent.service
systemctl daemon-reload
systemctl enable dgx-spark-bar-agent >/dev/null
systemctl restart dgx-spark-bar-agent

if [[ -d /etc/avahi/services ]]; then
  echo "==> mDNS advertisement"
  # The agent's VERSION is the only place the number is written; nothing reads
  # this TXT record back, so a hand-edited copy would drift unnoticed forever.
  AGENT_VERSION="$(sed -n 's/^VERSION = "\(.*\)"$/\1/p' "$SRC/dgx_spark_bar_agent.py" | head -1)"
  sed -e "s/@PORT@/$PORT/g" -e "s/@VERSION@/$AGENT_VERSION/g" \
    "$SRC/dgx-spark-bar.avahi.service" > /etc/avahi/services/dgx-spark-bar.service
  systemctl reload avahi-daemon 2>/dev/null || systemctl restart avahi-daemon || true
else
  echo "==> avahi not installed — LAN discovery off, tailnet discovery still works"
fi

sleep 1
systemctl is-active --quiet dgx-spark-bar-agent \
  && echo "==> running" \
  || { echo "!!  agent failed to start:"; journalctl -u dgx-spark-bar-agent -n 20 --no-pager; exit 1; }

LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
TS_IP="$(sudo -u "$TARGET_USER" tailscale ip -4 2>/dev/null | head -1 || true)"

echo
[[ -n "$TS_IP"  ]] && echo "tailnet: http://$TS_IP:$PORT/"
[[ -n "$LAN_IP" ]] && echo "lan:     http://$LAN_IP:$PORT/"
echo "The menu-bar client finds this box on its own — nothing to paste."
